/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginSignUp;
import Main.Contacts;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import Storage.storage;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

/**
 *
 * @author meraj
 */
public class login extends javax.swing.JFrame {
   private String user;
    /**
     * Creates new form SignUp
     */
    public login() {
        initComponents();
        jTxtUser.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            handleEnterKey(evt);
        }
        });
        jTxtPass.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            handleEnterKey(evt);
        }
       });
        
    }
    
    public  String getUserName() 
    {
        this.user = jTxtUser.getText();
        return user;
    }
    private void handleEnterKey(java.awt.event.KeyEvent evt){
        if(evt.getKeyCode() != java.awt.event.KeyEvent.VK_ENTER)return;
        if(jTxtUser.getText().isEmpty() || jTxtPass.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Username and Password cannot be empty.");
        }
        else{
            String db = "jdbc:mysql://localhost:3306/phonebook";
            String query = "SELECT * FROM login WHERE username = ? AND password = ?";
            java.sql.Connection con = null;
            try
            {
                con = DriverManager.getConnection(db, "root","root");
                PreparedStatement pstm = con.prepareStatement(query);
                pstm.setString(1, jTxtUser.getText());
                pstm.setString(2, jTxtPass.getText());
                ResultSet rs = pstm.executeQuery();
            
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this, "login Successfull!");
                    String user = jTxtUser.getText();
                    Contacts contact = new Contacts(user);
                    storage str = new storage(user);
//                Contacts.main(new String[]{user});
                    contact.setVisible(true);
                    this.dispose();           
                }
                else
                {
                  JOptionPane.showMessageDialog(this, "Invalid Credentials!");
                }
            }
            catch(SQLException ex)
            {
             ex.printStackTrace();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        loginDetailsPanel = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        jLUser = new javax.swing.JLabel();
        jTxtUser = new javax.swing.JTextField();
        jLPass = new javax.swing.JLabel();
        jTxtPass = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        signUp = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PhoneBook-Login");
        setBackground(new java.awt.Color(0, 255, 255));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        MainPanel.setBackground(new java.awt.Color(102, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MainPanelKeyTyped(evt);
            }
        });

        loginDetailsPanel.setBackground(new java.awt.Color(98, 235, 248));
        loginDetailsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginDetailsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginDetailsPanelMouseEntered(evt);
            }
        });
        loginDetailsPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginDetailsPanelKeyTyped(evt);
            }
        });
        loginDetailsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginSignUp/1.png"))); // NOI18N
        loginDetailsPanel.add(loginIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLUser.setText("USERNAME :");
        loginDetailsPanel.add(jLUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 87, -1));

        jTxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUserActionPerformed(evt);
            }
        });
        loginDetailsPanel.add(jTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 106, -1));

        jLPass.setText("PASSWORD :");
        loginDetailsPanel.add(jLPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 87, -1));
        loginDetailsPanel.add(jTxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 106, -1));

        Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        loginDetailsPanel.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        loginDetailsPanel.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        signUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUp.setText("New User ? Sign Up");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonListener(evt);
            }
        });
        loginDetailsPanel.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 165, 35));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), javax.swing.BorderFactory.createEtchedBorder()));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(loginDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(loginDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUserActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        jTxtUser.setText("");
        jTxtPass.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void SignUpButtonListener(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonListener
//                new signUp().setVisible(true);
        this.dispose(); // Close the current frame
                new signUp().setVisible(true);
    }//GEN-LAST:event_SignUpButtonListener

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    if(jTxtUser.getText().isEmpty() || jTxtPass.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Username and Password cannot be empty.");
    }
    else
    {
        String db = "jdbc:mysql://localhost:3306/phonebook";
        String query = "SELECT * FROM login WHERE username = ? AND password = ?";
        java.sql.Connection con = null;
        try
        {
            con = DriverManager.getConnection(db, "root","root");
            PreparedStatement pstm = con.prepareStatement(query);
            pstm.setString(1, jTxtUser.getText());
            pstm.setString(2, jTxtPass.getText());
            ResultSet rs = pstm.executeQuery();
            
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, "login Successfull!");
                String user = jTxtUser.getText();
                storage str = new storage(user);
//                Contacts.main(new String[]{user});
                new Contacts(user).setVisible(true);
                this.dispose();           
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid Credentials!");
            }
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
        }
    }
      
    }//GEN-LAST:event_SubmitActionPerformed

    private void loginDetailsPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginDetailsPanelKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() == '\n'){
            System.out.println("tesr");
            SubmitActionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "keyPress"));
        }
        else{
            System.out.println("dcw");
        }
    }//GEN-LAST:event_loginDetailsPanelKeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void loginDetailsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginDetailsPanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginDetailsPanelMouseEntered

    private void MainPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MainPanelKeyTyped
        System.out.println("rvr");
        // TODO add your handling code here:
    }//GEN-LAST:event_MainPanelKeyTyped

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }
    public  ArrayList <storageClass> list;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLPass;
    private javax.swing.JLabel jLUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtPass;
    private javax.swing.JTextField jTxtUser;
    private javax.swing.JPanel loginDetailsPanel;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel signUp;
    // End of variables declaration//GEN-END:variables
}
/*first_name varchar(50) 
                          last_name varchar(50) 
                          contact_number varchar(15) relation varchar(50) gmail varchar(100) is_blocked*/